name: CI на Gitverse
on:
  push:
jobs:
  build:
    name: Checkout and build
    runs-on: ubuntu-latest
    steps:      
      - 
        name: Checkout
        uses: actions/checkout@v2
      
      - name: Установка и обновление sudo для докера
        run: |
            apt update && apt install sudo     
            
      - 
        name: Установка docker
        run: |
          curl -sSL https://get.docker.com/ | sudo sh    
    
      - name: docker build
        working-directory: .
        run: |
            ls -l
            docker build . -t logtheday